### ISSUE TITLE
error: relation "post_un" already exists - when adding constraint

### ISSUE THREAD

**Issue by oste** [michaelsogos/pg-diff-api#12]
I added a unique constraint to my table and I am getting sql like this

```
--- BEGIN ALTER TABLE "public"."post" ---

ALTER TABLE IF EXISTS "public"."post" ADD CONSTRAINT "post_un" UNIQUE (some_col, another_col);

COMMENT ON CONSTRAINT "post_un" ON "public"."post" IS NULL;

-- CREATE UNIQUE INDEX post_un ON public.post USING btree (some_col, another_col);

COMMENT ON INDEX "public"."post"  IS NULL;

--- END ALTER TABLE "public"."post" ---
```

Notice I have commented out `-- CREATE UNIQUE INDEX post_un ON public.post USING btree (some_col, another_col);` if I don't do this I get the error error: relation "post_un" already exists. 

I think this part can be omitted from the queries since it will be automatically created.

**Comment by michaelsogos** [comment]
Hi @oste ,

This has been fixed in version 1.4.4.
